In [ ]:
import numpy as np
a = np.array([1, 2, 3])
print(a)


[1 2 3]


In [ ]:
a.ndim

1

In [ ]:
a.shape

(3,)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
a.data

**Array creation**

In [ ]:
# Converting Python sequences to NumPy arrays
import numpy as np
s1d = np.array([1,2,3])
s2d = np.array([[4,5,6],[7,8,9]])
s3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(s1d)
print(s2d)
print(s3d)

[1 2 3]
[[4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
 #Intrinsic NumPy array creation functions
 # 1D array creation
import numpy as np
a=np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b=np.linspace(1,10)
print(b)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [ ]:
# 2D array creation
c=np.eye(4,5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:
d =np.diag([1,2,3,4,5])
print(d)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
# nDarray creation
e=np.ones((2,5))
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
f = np.zeros((3,4))
print(f)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
s=np.indices((3,3))
print(s)

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


**Replicating,joining Arrays**

In [ ]:
#Replicating
import numpy as np
a=np.array([1,2,3])
print(np.repeat(a,2))
print(np.tile(a,3))

[1 1 2 2 3 3]
[1 2 3 1 2 3 1 2 3]


In [ ]:
#joining Arrays
#a) concatenate
import numpy as np
a=np.array([1,2,3,5])
b=np.array([5,6,7,8])
print(np.concatenate((a,b)))
#b) horizontaljoin
print(np.hstack((a,b)))
#c) vertical Join
print(np.vstack((a,b)))

[1 2 3 5 5 6 7 8]
[1 2 3 5 5 6 7 8]
[[1 2 3 5]
 [5 6 7 8]]


In [2]:
import numpy as np
arr=np.array([[1,2,3],[3,4,5],[6,7,8]])

In [3]:
arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr.T

array([[1, 3, 6],
       [2, 4, 7],
       [3, 5, 8]])

In [5]:
arr.argmax()

np.int64(8)

In [6]:
arr.argmin()

np.int64(0)

In [8]:
arr.sort()
arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
arr.ravel
arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
result = np.sqrt(arr)
print(result)

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


In [21]:
a = arr.size
print(a)

9
